name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "22"
          cache: "npm"

      - name: Install System Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libarchive-tools build-essential fakeroot rpm libfuse2

      - name: Install Dependencies
        run: npm ci

      - name: Build and Publish Artifacts
        run: npm run build && npx electron-builder --publish always
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: "false"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GETH_DATA_DIR: ${{ secrets.GETH_DATA_DIR }}
          GETH_NETWORK_ID: ${{ secrets.GETH_NETWORK_ID }}
          GETH_BOOTNODE_ENODE: ${{ secrets.GETH_BOOTNODE_ENODE }}
          GETH_GENESIS_PATH: ${{ secrets.GETH_GENESIS_PATH }}
          GETH_HTTP_HOST: ${{ secrets.GETH_HTTP_HOST }}
          GETH_HTTP_PORT: ${{ secrets.GETH_HTTP_PORT }}
          GETH_HTTP_API: ${{ secrets.GETH_HTTP_API }}
          GETH_P2P_PORT: ${{ secrets.GETH_P2P_PORT }}
          GETH_LOG_VERBOSITY: ${{ secrets.GETH_LOG_VERBOSITY }}
